#!/usr/bin/env python3
"""Read the templates and write down what the theme reads and defines.

Four lists. The front matter keys a template reads. The site parameters
it reads. The shortcodes it defines. The words it renders.

Together they are the contract between a theme and a site. A site's
own content tooling can read it to learn what the theme understands.
This pipeline never reads content against it: sample content is test
data, and its prose is nobody's to grade.
"""

import os
import re
import sys

PARAMS = re.compile(r"\.Params\.([A-Za-z_][\w]*)")
SITE_PARAMS = re.compile(r"(?:site|\.Site)\.Params\.([A-Za-z_][\w]*)")
I18N = re.compile(r'\b(?:i18n|T)\s+"([^"]+)"')
FEATURE = re.compile(r"^\s*name\s*=\s*[\"']([^\"']+)")


def partials_dir():
    for candidate in ("layouts/_partials", "layouts/partials"):
        if os.path.isdir(candidate):
            return candidate
    return "layouts"


def templates():
    for folder, dirs, files in os.walk("layouts"):
        dirs[:] = sorted(dirs)
        for name in sorted(files):
            if name.endswith(".html"):
                yield os.path.join(folder, name)


def shortcodes():
    out = []
    for base in ("layouts/shortcodes", "layouts/_shortcodes"):
        if os.path.isdir(base):
            for name in sorted(os.listdir(base)):
                stem, ext = os.path.splitext(name)
                if ext in (".html", ".md"):
                    out.append(stem)
    return sorted(set(out))


def features():
    out = []
    folder = "data/features"
    if os.path.isdir(folder):
        for name in sorted(os.listdir(folder)):
            if not name.endswith(".toml"):
                continue
            with open(os.path.join(folder, name), encoding="utf-8") as handle:
                for line in handle:
                    match = FEATURE.match(line)
                    if match:
                        out.append(match.group(1))
                        break
    return sorted(set(out))


def scan():
    front, site, words = set(), set(), set()
    for path in templates():
        with open(path, encoding="utf-8", errors="replace") as handle:
            text = handle.read()
        site.update(SITE_PARAMS.findall(text))
        for name in PARAMS.findall(text):
            front.add(name)
        words.update(I18N.findall(text))
    front -= site
    return sorted(front), sorted(site), sorted(words)


def array(name, values):
    if not values:
        return "%s = []\n" % name
    body = "".join('  "%s",\n' % value for value in values)
    return "%s = [\n%s]\n" % (name, body)


def render():
    front, site, words = scan()
    codes = shortcodes()
    parts = [
        "# What this theme reads and what it defines. Generated by ./c docs.\n"
        "# A site's content tooling can read this file to learn what the\n"
        "# theme understands.\n\n",
        array("front_matter", front),
        array("params", site),
        array("shortcodes", codes),
        array("i18n", words),
        array("features", features()),
    ]
    return "".join(parts)


def front_matter_doc():
    front, site, words = scan()
    lines = [
        "# Front matter\n",
        "\n",
        "Generated by `./c docs`. Every key below is read by a template in\n"
        "this theme. A key absent from a page falls back to whatever the\n"
        "template does with an empty value.\n",
        "\n",
        "## Page keys\n",
        "\n",
    ]
    if front:
        lines.append("| Key | Read as |\n|---|---|\n")
        for name in front:
            lines.append("| `%s` | `.Params.%s` |\n" % (name, name))
    else:
        lines.append("No page key is read by a template.\n")
    lines.extend(["\n", "## Site parameters\n", "\n"])
    if site:
        lines.append("| Key | Read as |\n|---|---|\n")
        for name in site:
            lines.append("| `%s` | `site.Params.%s` |\n" % (name, name))
    else:
        lines.append("No site parameter is read by a template.\n")
    lines.extend(["\n", "## Words\n", "\n"])
    if words:
        lines.append("| Key |\n|---|\n")
        for name in words:
            lines.append("| `%s` |\n" % name)
    else:
        lines.append("No i18n key is used by a template.\n")
    return "".join(lines)


def write_pair(root):
    """Write both generated files under root, in their usual places."""
    with open(os.path.join(root, "contract.toml"), "w", encoding="utf-8") as handle:
        handle.write(render())
    os.makedirs(os.path.join(root, "docs"), exist_ok=True)
    with open(os.path.join(root, "docs", "front-matter.md"), "w", encoding="utf-8") as handle:
        handle.write(front_matter_doc())


def main():
    argv = sys.argv[1:]
    if "--stdout" in argv:
        sys.stdout.write(render())
        return 0

    # --into writes the same pair somewhere else. Both files are
    # generated from the same templates, so the gate has to compare
    # both. That needs a fresh copy of each, and not the checked-in
    # ones.
    if "--into" in argv:
        index = argv.index("--into") + 1
        if index >= len(argv):
            sys.stderr.write("--into needs a directory\n")
            return 1
        write_pair(argv[index])
        return 0

    write_pair(".")
    print("contract.toml and docs/front-matter.md regenerated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
