#!/usr/bin/env bash
# Give the theme its own code colours.
#
# Chroma writes colours into the markup as inline styles by default.
# Nothing can override an inline style, and Chroma's line numbers are
# #7f7f7f, which is 4.0 to 1 on white and below AA.
#
# With classes the theme owns the colours. The stylesheet is generated
# from a named style, and the line numbers are darkened to pass.
set -euo pipefail
cd "$(dirname "$0")/../.." || exit 1

STYLE="${CHROMA_STYLE:-xcode}"
sheet=assets/css/chroma.css
[ -f "$sheet" ] && exit 0

mkdir -p assets/css
# Generated by Chroma, so it is not held to the house comment rules.
printf '%s\n' "/* Generated by hugo gen chromastyles. docs-style:ignore-file */" > "$sheet"
hugo gen chromastyles --style="$STYLE" >> "$sheet"
cat >> "$sheet" <<'CSS'

/* Chroma sets line numbers to #7f7f7f, which is 4.0 to 1 on white.
   #595959 is 7.0 to 1, which clears AA and AAA for body text. */
.chroma .lnt,
.chroma .ln {
  color: #595959;
}
CSS

# The theme says the same thing to whoever installs it. A site config
# overrides this, which is how the conformance build sets it too.
if ! grep -q 'markup.highlight' hugo.toml; then
  cat >> hugo.toml <<'TOML'

[markup]
  [markup.highlight]
    noClasses = false
    style = 'xcode'
TOML
fi
